# Copyright 2017 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD license
# that can be found in the LICENSE file.

# https://manski.net/2016/09/vagrant-multi-machine-tutorial/

BOX_IMAGE = "centos/7"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
	config.vm.define "master" do |subconfig|
		subconfig.vm.box = BOX_IMAGE
		subconfig.vm.box_check_update = false

		subconfig.vm.hostname = "master"
		subconfig.vm.network :private_network, ip: "10.0.0.100"
	end

	(1..NODE_COUNT).each do |i|
		config.vm.define "node#{i}" do |subconfig|
			subconfig.vm.box = BOX_IMAGE
			subconfig.vm.box_check_update = false

			subconfig.vm.hostname = "node#{i}"
			subconfig.vm.network :private_network, ip: "10.0.0.#{100+i}"
		end
	end

	# Install avahi on all machines
	# sudo service avahi-daemon status
	# sudo service avahi-daemon restart
	config.vm.provision "shell", inline: <<-SHELL
		sudo yum install -y avahi-tools avahi-ui-tools
		echo Hello
	SHELL
end
