# Copyright 2017 ChaiShushan<chaishushan@gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

FROM scratch
ADD hello_v2.linux.exe /
CMD ["/hello_v2.linux.exe"]
